version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directories:
      - "/apps/api"
      - "/apps/cron"
      - "/apps/migrate"
      - "/apps/web"
      - "/apps/ws"
      - "/infra/proxy"
    schedule:
      interval: "daily"
    groups:
      docker-images:
        patterns:
          - "*"
    open-pull-requests-limit: 10
