FROM oven/bun:1.4.0-alpine@sha256:07235578f79ef8c6f97d94aee7938e76f5cdba5f21ae5dbfdd3d3d38058437eb AS pruner
WORKDIR /app
COPY . .
RUN bunx turbo prune @app/migrate --docker

FROM oven/bun:1.4.0-alpine@sha256:07235578f79ef8c6f97d94aee7938e76f5cdba5f21ae5dbfdd3d3d38058437eb AS build
WORKDIR /app
COPY --from=pruner /app/out/json/ .
RUN bun install --frozen-lockfile
COPY --from=pruner /app/out/full/ .
COPY --from=pruner /app/tsconfig.base.json ./
RUN bun run --filter=@app/migrate build

FROM oven/bun:1.4.0-alpine@sha256:07235578f79ef8c6f97d94aee7938e76f5cdba5f21ae5dbfdd3d3d38058437eb AS runtime
WORKDIR /app

COPY --from=build /app/apps/migrate/dist ./apps/migrate/dist
COPY --from=build /app/apps/migrate/src/migrations ./apps/migrate/dist/migrations

USER bun
CMD ["bun", "apps/migrate/dist/migrate.js"]
