import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");

const colorsFile = Bun.file(join(ROOT, "packages/theme/colors.json"));
const colors: { dark: Record<string, string>; light: Record<string, string> } =
  await colorsFile.json();

// Preserve existing utility names while using the installed UI package theme.
// packages/theme/colors.json remains the standalone proxy loading-page palette.
const aliases: Record<string, string> = {
  "bg": "bg",
  "bg-raised": "bg-2",
  "bg-card": "surface-3",
  "bg-input": "input",
  "bg-hover": "hover",
  "border": "border",
  "border-focus": "border-strong",
  "text": "text",
  "text-muted": "text-dim",
  "text-faint": "text-mute",
  "accent-green": "green",
  "accent-amber": "amber",
  "accent-purple": "accent",
  "accent-blue": "blue",
  "accent-rose": "red",
  "primary": "primary",
  "primary-hover": "primary-hover"
};
const colorsCss = `/* Generated by scripts/sync-theme.ts. Legacy utilities follow the shared UI theme. */
@theme inline {
${Object.entries(aliases).map(([name, token]) => `  --color-${name}: var(--bnh-${token});`).join("\n")}
}
`;

await Bun.write(join(ROOT, "apps/web/src/app/colors.css"), colorsCss);
console.log("Generated apps/web/src/app/colors.css");

// Generate loading page from template
const templatePath = join(ROOT, "infra/proxy/loading.template.html");
const outputPath = join(ROOT, "infra/proxy/loading.html");

try {
  const template = await Bun.file(templatePath).text();
  const rootVars = Object.entries(colors.dark)
    .map(([key, value]) => `      --color-${key}: ${value};`)
    .join("\n");
  const rootBlock = `:root {\n${rootVars}\n    }`;
  const loadingHtml =
    "<!-- AUTO-GENERATED — edit loading.template.html, then run: bun scripts/sync-theme.ts -->\n" +
    template.replace("/* THEME_VARS */", rootBlock);
  await Bun.write(outputPath, loadingHtml);
  console.log("Generated infra/proxy/loading.html");
} catch {
  console.log("No loading template found, skipping loading.html generation");
}
